# Generated by Django 5.1.3 on 2024-11-24 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendInapp', '0002_auto_20241124_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='end_time',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='start_time',
            new_name='open_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='location',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='cuisine',
            field=models.CharField(choices=[('asian', 'Asian'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('american', 'American'), ('indian', 'Indian'), ('other', 'Other')], default='Not Specified', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operatingday',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
