# Generated by Django 5.1.3 on 2024-11-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendInapp', '0003_alter_vendor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('FOOD_FESTIVAL', 'Food Festival'), ('MARKET', 'Food Market'), ('POPUP', 'Pop-up Event')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
