# Generated by Django 5.1.3 on 2024-11-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendInapp', '0005_alter_event_options_event_created_at_event_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('user_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
